<?php

?>
<html>
<head>
    	
        <title>DLCF PS - Admin Page</title>
        
        <link rel="stylesheet" type="text/css" href="../css/main.css" />
        
        <style type="text/css">
		input[type=submit]{
			font-weight:bold;
			margin-left:14px;
			border: 1px solid #aaa;
			padding: 3px 7px;
			color:#FFF;
			text-decoration: none;
			background: #ddd;
		
			border-radius: 12px;
			-webkit-border-radius: 12px;
			-moz-border-radius: 12px;
		
			text-shadow: 0 1px 0 #fff;
		
			background-image: url(svg_gradient.php?from=ffffff&to=000000);
		background-size: 100% 100%;
		background: -webkit-gradient(linear, left top, left bottom, from(#ffffff), to(#000000));
		background: -webkit-linear-gradient(top, #ffffff, #000000);
		background: -moz-linear-gradient(top, #ffffff, #000000);
		background: -ms-linear-gradient(top, #ffffff, #000000);
		background: -o-linear-gradient(top, #ffffff, #000000);}
		
		input[type=submit]:hover{position: relative;
			background-image: url(svg_gradient.php?from=000000&to=dddddd);
		background-size: 100% 100%;
		background: -webkit-gradient(linear, left top, left bottom, from(#000000), to(#dddddd));
		background: -webkit-linear-gradient(top, #000000, #dddddd);
		background: -moz-linear-gradient(top, #000000, #dddddd);
		background: -ms-linear-gradient(top, #000000, #dddddd);
		background: -o-linear-gradient(top, #000000, #dddddd);    cursor:pointer;
		}
		
		input[type=submit]:active{position: relative;
			top: 1px;
			left: 1px;
		}
		</style>
        
    </head>
    
    <body>
    
  <div id="main_body">
        
        	<div style="height:145px;">
            
            	<!--<div style="margin-top:0px; vertical-align:top; float:right">
                    <img src="images/banner.png" />
                    <br/>
                    <span style="text-align:center; font-size:18px; margin-left:220px">...aggressive evangelism</span> 
                </div>-->
			 <div style="margin-top:0px; vertical-align:top; text-align:center">
			 	<span style="font-size:50px;">Depper Life</span><br />
				<span style="font-size:50px">Campus Fellowship</span>
			 </div>
                
            	<!--<img src="images/rcf.png" style="margin-left:5px; margin-top:4px;"/>-->
                                              
            </div>
            
            <div id="area" style="text-align:center"><br>
            	
            	<h2><center>Welcome to Deeper Life Campus Fellowship CBT Admin Page. </center></h2>
                <br>
                <h3><center>Click the Link Below to Check Result</center></h3>
                <br>
              <a href="result.php" title=""><b>Check Result</b></a>
            	<!--<div style="margin-top:250px; vertical-align:bottom;">
                	<marquee direction="left" scrollamount="5">...the happiest people on campus</marquee>
                </div>-->
            </div>
            
   	</div>
    	
    </body>
    
</html>